import 'package:flutter/material.dart';
{{#isRiverpod}}import 'package:flutter_riverpod/flutter_riverpod.dart';{{/isRiverpod}}
{{#isBloc}}import 'package:flutter_bloc/flutter_bloc.dart';{{/isBloc}}
{{#isProvider}}import 'package:provider/provider.dart';{{/isProvider}}
import 'core/router/router.dart';
import 'core/theme/app_theme.dart';
import 'core/theme/theme_mode_notifier.dart';
{{#isAutoRoute}}import 'package:auto_route/auto_route.dart';{{/isAutoRoute}}


import 'package:{{name.snakeCase()}}/core/theme/theme_mode_notifier.dart';
import 'package:{{name.snakeCase()}}/shared/design_system/tokens/app_border_radius.dart';
import 'package:{{name.snakeCase()}}/shared/design_system/tokens/app_responsive.dart';
import 'package:{{name.snakeCase()}}/shared/design_system/tokens/app_spacing.dart';
import 'package:{{name.snakeCase()}}/shared/design_system/buttons/primary_button.dart';
import 'package:{{name.snakeCase()}}/shared/design_system/inputs/primary_input.dart';
import 'package:{{name.snakeCase()}}/shared/design_system/buttons/text_button.dart';

void main() {
  runApp(
    {{#isRiverpod}}const ProviderScope(child: MyApp()){{/isRiverpod}}{{#isBloc}}BlocProvider(create: (_) => ThemeCubit(), child: const MyApp()){{/isBloc}}{{#isProvider}}MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
      ],
      child: const MyApp(),
    ){{/isProvider}}{{#isNone}}const MyApp(){{/isNone}}
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    {{#isRiverpod}}
    return Consumer(
      builder: (context, ref, child) {
        final themeMode = ref.watch(themeModeProvider);
        {{#isAutoRoute}}
        final appRouter = AppRouter();
        {{/isAutoRoute}}
        return MaterialApp.router(
          title: '{{name.titleCase()}}',
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode: themeMode,
          {{#isGoRouter}}routerConfig: router,{{/isGoRouter}}
          {{#isAutoRoute}}routerConfig: appRouter.config(),{{/isAutoRoute}}
        );
      },
    );
    {{/isRiverpod}}{{#isBloc}}
    return BlocBuilder<ThemeCubit, ThemeMode>(
      builder: (context, themeMode) {
        {{#isAutoRoute}}
        final appRouter = AppRouter();
        {{/isAutoRoute}}
        return MaterialApp.router(
          title: '{{name.titleCase()}}',
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode: themeMode,
          {{#isGoRouter}}routerConfig: router,{{/isGoRouter}}
          {{#isAutoRoute}}routerConfig: appRouter.config(),{{/isAutoRoute}}
        );
      },
    );
    {{/isBloc}}{{#isProvider}}
    return Consumer<ThemeProvider>(
      builder: (context, themeProvider, child) {
        {{#isAutoRoute}}
        final appRouter = AppRouter();
        {{/isAutoRoute}}
        return MaterialApp.router(
          title: '{{name.titleCase()}}',
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode: themeProvider.themeMode,
          {{#isGoRouter}}routerConfig: router,{{/isGoRouter}}
          {{#isAutoRoute}}routerConfig: appRouter.config(),{{/isAutoRoute}}
        );
      },
    );
    {{/isProvider}}{{#isNone}}
    return ListenableBuilder(
      listenable: themeNotifier,
      builder: (context, child) {
        {{#isAutoRoute}}
        final appRouter = AppRouter();
        {{/isAutoRoute}}
        return MaterialApp.router(
          title: '{{name.titleCase()}}',
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode: themeNotifier.themeMode,
          {{#isGoRouter}}routerConfig: router,{{/isGoRouter}}
          {{#isAutoRoute}}routerConfig: appRouter.config(),{{/isAutoRoute}}
        );
      },
    );
    {{/isNone}}
  }
}



// TODO: This HomeScreen is a boilerplate design system showcase generated by zuq CLI.
// It is safe to delete or replace once you start building your application.

{{#isAutoRoute}}
@RoutePage()
{{/isAutoRoute}}
class HomeScreen extends {{#isRiverpod}}ConsumerStatefulWidget{{/isRiverpod}}{{^isRiverpod}}StatefulWidget{{/isRiverpod}} {
  const HomeScreen({super.key});

  @override
  {{#isRiverpod}}ConsumerState<HomeScreen>{{/isRiverpod}}{{^isRiverpod}}State<HomeScreen>{{/isRiverpod}} createState() => _HomeScreenState();
}

class _HomeScreenState extends {{#isRiverpod}}ConsumerState<HomeScreen>{{/isRiverpod}}{{^isRiverpod}}State<HomeScreen>{{/isRiverpod}} {
  final _formKey = GlobalKey<FormState>();
  bool _isBtnLoading = false;

  void _handleToggleTheme() {
    {{#isRiverpod}}
    ref.read(themeModeProvider.notifier).toggleTheme();
    {{/isRiverpod}}
    {{#isBloc}}
    context.read<ThemeCubit>().toggleTheme();
    {{/isBloc}}
    {{#isProvider}}
    Provider.of<ThemeProvider>(context, listen: false).toggleTheme();
    {{/isProvider}}
    {{#isNone}}
    themeNotifier.toggleTheme();
    {{/isNone}}
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Zuq Design System'),
        elevation: 0,
        actions: [
          IconButton(
            icon: Icon(isDark ? Icons.light_mode_rounded : Icons.dark_mode_rounded),
            onPressed: _handleToggleTheme,
            tooltip: 'Toggle Theme Mode',
          ),
        ],
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(AppSpacing.m),
          child: Center(
            child: Container(
              constraints: const BoxConstraints(maxWidth: 800),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Header Card with beautiful Gradient
                  Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(AppSpacing.l),
                    decoration: BoxDecoration(
                      borderRadius: AppBorderRadius.allL,
                      gradient: LinearGradient(
                        colors: [
                          theme.colorScheme.primary,
                          theme.colorScheme.secondary,
                        ],
                        begin: Alignment.topLeft,
                        end: Alignment.bottomRight,
                      ),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Welcome to {{name.titleCase()}}',
                          style: theme.textTheme.headlineMedium?.copyWith(
                            color: theme.colorScheme.onPrimary,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        AppSpacing.vXS,
                        Text(
                          'This is your premium responsive design system showcase.',
                          style: theme.textTheme.bodyLarge?.copyWith(
                            color: theme.colorScheme.onPrimary.withValues(alpha: 0.8),
                          ),
                        ),
                      ],
                    ),
                  ),
                  AppSpacing.vL,

                  // Section Title
                  Text(
                    'Responsive Layouts',
                    style: theme.textTheme.titleLarge?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  AppSpacing.vS,

                  // Responsive columns
                  LayoutBuilder(
                    builder: (context, constraints) {
                      final columnsCount = context.responsive<int>(
                        mobile: 1,
                        tablet: 2,
                        desktop: 3,
                      );

                      final titles = [
                        'Adaptive Grid',
                        'Responsive Spacing',
                        'Fluid Typography',
                      ];
                      final descriptions = [
                        'Columns dynamically scale between Mobile (1), Tablet (2), and Desktop (3).',
                        'AppSpacing tokens automatically adapt to standard screen layouts.',
                        'Font sizes and margins adjust gracefully across varying window ratios.',
                      ];

                      return GridView.builder(
                        shrinkWrap: true,
                        physics: const NeverScrollableScrollPhysics(),
                        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                          crossAxisCount: columnsCount,
                          crossAxisSpacing: AppSpacing.m,
                          mainAxisSpacing: AppSpacing.m,
                          childAspectRatio: 2.2,
                        ),
                        itemCount: 3,
                        itemBuilder: (context, index) {
                          return Container(
                            decoration: BoxDecoration(
                              color: theme.colorScheme.surface,
                              borderRadius: AppBorderRadius.allM,
                              border: Border.all(
                                color: theme.colorScheme.outline.withValues(alpha: 0.1),
                              ),
                            ),
                            child: Padding(
                              padding: const EdgeInsets.all(AppSpacing.m),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: [
                                  Text(
                                    titles[index],
                                    style: theme.textTheme.titleMedium?.copyWith(
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                  AppSpacing.vXXS,
                                  Expanded(
                                    child: Text(
                                      descriptions[index],
                                      style: theme.textTheme.bodyMedium?.copyWith(
                                        color: theme.colorScheme.onSurface.withValues(alpha: 0.7),
                                      ),
                                      maxLines: 3,
                                      overflow: TextOverflow.ellipsis,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          );
                        },
                      );
                    },
                  ),
                  AppSpacing.vL,

                  // Section Title: Forms & Inputs
                  Text(
                    'Form Inputs & Controls',
                    style: theme.textTheme.titleLarge?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  AppSpacing.vS,
                  Form(
                    key: _formKey,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const PrimaryInput(
                          labelText: 'Email Address',
                          hintText: 'enter your email address',
                          prefixIcon: Icon(Icons.email_outlined),
                          keyboardType: TextInputType.emailAddress,
                        ),
                        AppSpacing.vM,
                        const PrimaryInput(
                          labelText: 'Password',
                          hintText: '••••••••',
                          obscureText: true,
                          prefixIcon: Icon(Icons.lock_outline),
                        ),
                        AppSpacing.vL,
                        Row(
                          children: [
                            PrimaryButton(
                              text: 'Submit Action',
                              isLoading: _isBtnLoading,
                              icon: Icons.check_circle_outline,
                              onPressed: () async {
                                setState(() {
                                  _isBtnLoading = true;
                                });
                                await Future.delayed(const Duration(seconds: 2));
                                if (context.mounted) {
                                  setState(() {
                                    _isBtnLoading = false;
                                  });
                                  ScaffoldMessenger.of(context).showSnackBar(
                                    const SnackBar(
                                      content: Text('Form submitted successfully!'),
                                      behavior: SnackBarBehavior.floating,
                                    ),
                                  );
                                }
                              },
                            ),
                            AppSpacing.hS,
                            AppTextButton(
                              text: 'Forgot Password?',
                              onPressed: () {},
                              icon: Icons.help_outline,
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
