import 'package:flutter/material.dart';
{{#isRiverpod}}import 'package:flutter_riverpod/flutter_riverpod.dart';{{/isRiverpod}}
{{#isBloc}}import 'package:flutter_bloc/flutter_bloc.dart';{{/isBloc}}
{{#isProvider}}import 'package:provider/provider.dart';{{/isProvider}}
import 'core/router/router.dart';
import 'core/theme/app_theme.dart';
import 'core/theme/theme_mode_notifier.dart';
{{#isAutoRoute}}import 'package:auto_route/auto_route.dart';{{/isAutoRoute}}

import 'package:{{name.snakeCase()}}/shared/design_system/tokens/app_border_radius.dart';
import 'package:{{name.snakeCase()}}/shared/design_system/tokens/app_spacing.dart';
import 'package:{{name.snakeCase()}}/shared/design_system/tokens/app_font_weight.dart';
import 'package:{{name.snakeCase()}}/shared/design_system/tokens/app_line_height.dart';
import 'package:{{name.snakeCase()}}/shared/design_system/tokens/app_letter_spacing.dart';
import 'package:{{name.snakeCase()}}/shared/design_system/tokens/app_border_width.dart';
import 'package:{{name.snakeCase()}}/shared/design_system/tokens/app_icon_size.dart';
import 'package:{{name.snakeCase()}}/shared/design_system/tokens/brand_colors.dart';

void main() {
  runApp(
    {{#isRiverpod}}const ProviderScope(child: MyApp()){{/isRiverpod}}{{#isBloc}}BlocProvider(create: (_) => ThemeCubit(), child: const MyApp()){{/isBloc}}{{#isProvider}}MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
      ],
      child: const MyApp(),
    ){{/isProvider}}{{#isNone}}const MyApp(){{/isNone}}
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    {{#isRiverpod}}
    return Consumer(
      builder: (context, ref, child) {
        final themeMode = ref.watch(themeModeProvider);
        {{#isAutoRoute}}
        final appRouter = AppRouter();
        {{/isAutoRoute}}
        return MaterialApp.router(
          title: '{{name.titleCase()}}',
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode: themeMode,
          {{#isGoRouter}}routerConfig: router,{{/isGoRouter}}
          {{#isAutoRoute}}routerConfig: appRouter.config(),{{/isAutoRoute}}
        );
      },
    );
    {{/isRiverpod}}{{#isBloc}}
    return BlocBuilder<ThemeCubit, ThemeMode>(
      builder: (context, themeMode) {
        {{#isAutoRoute}}
        final appRouter = AppRouter();
        {{/isAutoRoute}}
        return MaterialApp.router(
          title: '{{name.titleCase()}}',
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode: themeMode,
          {{#isGoRouter}}routerConfig: router,{{/isGoRouter}}
          {{#isAutoRoute}}routerConfig: appRouter.config(),{{/isAutoRoute}}
        );
      },
    );
    {{/isBloc}}{{#isProvider}}
    return Consumer<ThemeProvider>(
      builder: (context, themeProvider, child) {
        {{#isAutoRoute}}
        final appRouter = AppRouter();
        {{/isAutoRoute}}
        return MaterialApp.router(
          title: '{{name.titleCase()}}',
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode: themeProvider.themeMode,
          {{#isGoRouter}}routerConfig: router,{{/isGoRouter}}
          {{#isAutoRoute}}routerConfig: appRouter.config(),{{/isAutoRoute}}
        );
      },
    );
    {{/isProvider}}{{#isNone}}
    return ListenableBuilder(
      listenable: themeNotifier,
      builder: (context, child) {
        {{#isAutoRoute}}
        final appRouter = AppRouter();
        {{/isAutoRoute}}
        return MaterialApp.router(
          title: '{{name.titleCase()}}',
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode: themeNotifier.themeMode,
          {{#isGoRouter}}routerConfig: router,{{/isGoRouter}}
          {{#isAutoRoute}}routerConfig: appRouter.config(),{{/isAutoRoute}}
        );
      },
    );
    {{/isNone}}
  }
}



// TODO: This HomeScreen is a boilerplate design system showcase generated by zuq CLI.
// It is safe to delete or replace once you start building your application.

{{#isAutoRoute}}
@RoutePage()
{{/isAutoRoute}}
class HomeScreen extends {{#isRiverpod}}ConsumerStatefulWidget{{/isRiverpod}}{{^isRiverpod}}StatefulWidget{{/isRiverpod}} {
  const HomeScreen({super.key});

  @override
  {{#isRiverpod}}ConsumerState<HomeScreen>{{/isRiverpod}}{{^isRiverpod}}State<HomeScreen>{{/isRiverpod}} createState() => _HomeScreenState();
}

class _HomeScreenState extends {{#isRiverpod}}ConsumerState<HomeScreen>{{/isRiverpod}}{{^isRiverpod}}State<HomeScreen>{{/isRiverpod}} {
  void _handleToggleTheme() {
    {{#isRiverpod}}
    ref.read(themeModeProvider.notifier).toggleTheme();
    {{/isRiverpod}}{{#isBloc}}
    context.read<ThemeCubit>().toggleTheme();
    {{/isBloc}}{{#isProvider}}
    Provider.of<ThemeProvider>(context, listen: false).toggleTheme();
    {{/isProvider}}{{#isNone}}
    themeNotifier.toggleTheme();
    {{/isNone}}
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final brandColors = context.brandColors;

    return Scaffold(
      backgroundColor: theme.colorScheme.surface,
      body: SafeArea(
        child: Center(
          child: Padding(
            padding: const EdgeInsets.all(AppSpacing.l),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                // Centered dynamic Logo Mark
                Container(
                  width: 80,
                  height: 80,
                  decoration: BoxDecoration(
                    color: brandColors.dark,
                    borderRadius: AppBorderRadius.allXL,
                    boxShadow: [
                      BoxShadow(
                        color: brandColors.mid.withValues(alpha: 0.15),
                        blurRadius: 20,
                        offset: const Offset(0, 8),
                      ),
                    ],
                  ),
                  alignment: Alignment.center,
                  child: Text(
                    '⚡',
                    style: theme.textTheme.headlineLarge?.copyWith(
                      fontSize: 38,
                      color: isDark ? brandColors.subtle : Colors.white,
                    ),
                  ),
                ),
                AppSpacing.vL,

                // App Name
                Text(
                  '{{name}}',
                  style: theme.textTheme.headlineMedium?.copyWith(
                    fontWeight: AppFontWeight.bold,
                    color: theme.colorScheme.onSurface,
                  ),
                ),
                AppSpacing.vXS,

                // Subtitle
                Text(
                  'Clean Architecture Boilerplate',
                  style: theme.textTheme.bodyMedium?.copyWith(
                    color: theme.colorScheme.onSurfaceVariant,
                    height: AppLineHeight.body,
                  ),
                ),
                AppSpacing.vL,

                // Custom Premium Theme Toggle Button
                GestureDetector(
                  onTap: _handleToggleTheme,
                  child: Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: AppSpacing.m,
                      vertical: AppSpacing.s,
                    ),
                    decoration: BoxDecoration(
                      color: theme.colorScheme.surfaceContainerLow,
                      borderRadius: AppBorderRadius.pill,
                      border: Border.all(
                        color: theme.colorScheme.outlineVariant.withValues(alpha: 0.5),
                        width: AppBorderWidth.hairline,
                      ),
                    ),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Icon(
                          isDark ? Icons.light_mode_rounded : Icons.dark_mode_rounded,
                          size: AppIconSize.s,
                          color: brandColors.mid,
                        ),
                        AppSpacing.hS,
                        Text(
                          isDark ? 'LIGHT MODE' : 'DARK MODE',
                          style: theme.textTheme.labelMedium?.copyWith(
                            fontWeight: AppFontWeight.medium,
                            color: theme.colorScheme.onSurface,
                            letterSpacing: AppLetterSpacing.label,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                AppSpacing.vXL,

                // Tech stack info pill
                Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: AppSpacing.m,
                    vertical: AppSpacing.xs,
                  ),
                  decoration: BoxDecoration(
                    color: brandColors.subtle,
                    borderRadius: AppBorderRadius.pill,
                  ),
                  child: Text(
                    'State: {{stateName}}  •  Router: {{routerName}}',
                    style: theme.textTheme.labelSmall?.copyWith(
                      color: brandColors.mid,
                      fontWeight: AppFontWeight.medium,
                      letterSpacing: AppLetterSpacing.label,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}