import 'package:flutter/material.dart';
{{#isGoRouter}}
import 'package:go_router/go_router.dart';
import 'routes.dart';

final router = GoRouter(
  initialLocation: Routes.home,
  routes: [
    GoRoute(
      path: Routes.home,
      builder: (context, state) => const Scaffold(
        body: Center(
          child: Text('Welcome to {{name.pascalCase()}}!'),
        ),
      ),
    ),
  ],
);
{{/isGoRouter}}
{{#isAutoRoute}}
import 'package:auto_route/auto_route.dart';
import 'routes.dart';
import 'router.gr.dart'; // generated by auto_route_generator

@AutoRouterConfig()
class AppRouter extends RootStackRouter {
  @override
  List<AutoRoute> get routes => [
    // AutoRoute(path: Routes.home, page: HomeRoute.page, initial: true),
  ];
}
{{/isAutoRoute}}
